const body2_data = [
    {
        title:'戰鬥玩法',
        img:'./images/body2-click.png',
        text:'玩家一次可以選擇四名角色參與戰鬥，並且在戰鬥中可以快速切換。角色可以通過各種方式增強他們的力量，例如提高角色的等級，改進角色裝備的聖遺物和武器。',
    },
    {
        title:'探險玩法',
        img:'./images/body2-click2.png',
        text:'遊戲採用開放世界地圖，除了正常的步行外，玩家可以透過攀爬、游泳、滑翔等移動手段來探索各式各樣的遺跡和地形',
    },
    {
        title:'技能介紹',
        img:'./images/body2-click3.png',
        text:'每個角色都有元素戰技與元素爆發兩種技能，元素戰技只要招式的冷卻時間結束就可以發動，元素爆發則需要累積一定的元素能量才可釋放。角色可以控制七種自然元素冰、草、火、水、風、雷、岩之一。這些元素可以以不同的方式相互作用，在戰鬥中切換角色並執行這些技能可以讓這些元素互動發生。',
    },
    {
        title:'抽卡玩法',
        img:'./images/body2-click4.png',
        text:'通過完成推進故事的任務，玩家最初可以解鎖四個額外的可玩角色，並且可以通過抽獎機制和遊戲內事件獲得更多角色。可以通過遊戲內事件或應用內購買獲得幾種高級遊戲貨幣，這些進階遊戲貨幣可以用來抽獎，玩家在一定次數的抽獎後，獲得稀有物品的概率會提升。',
    },
]

const shop_data = [
    {
        img:"./images/shop-1.png",
        img2:"./images/shop-1-2.png",
        title:"原神Q版鑰匙扣吊飾",
        text:"包裝：透明pp袋卡紙<br>材質：亞克力",
        price:75,
        b:'個',
        amount:0,
    },
    {
        img:"./images/shop-2.png",
        img2:"./images/shop-2-2.png",
        title:"原神甘雨公仔",
        text:"超限量原神甘雨公仔，你值得擁有",
        price:3800,
        b:'個',
        amount:0,
    },
    {
        img:"./images/shop-3.png",
        img2:"./images/shop-3-2.png",
        title:"原神T恤",
        text:"喜歡原神的你千萬別錯過,印有原神圖案的T恤",
        price:170,
        b:'件',
        amount:0,
    },
    {
        img:"./images/shop-4.png",
        img2:"./images/shop-4-2.png",
        title:"原神娃娃",
        text:"可愛毛茸茸的小娃娃,就這樣字數不夠",
        price:90,
        b:'個',
        amount:0,
    },
]

const robot_data = {
    '原神':'原神是目前最受人喜歡的遊戲，遊戲裡有精美的角色與開放世界探險，等著你一起去探險',
    '最強角色':'最強角色夜蘭六命，史上最扯的傷害瞬間秒掉boss的超強六命神角',
    '我抽卡都歪怎麼解決':'你這問題問我幹嘛，你要抽卡歪了表示說你是那50%幸運的人',
}
const robot_url = {
    '原神':'body1',
    '最強角色':'body3',
    '我抽卡都歪怎麼解決':'body6',
}